services:
    mongo:
        image: mongo
        container_name: mongodb
        restart: always
        ports:
            - 27017:27017
        command: mongod --replSet rs0 --bind_ip_all

    redis:
        image: redis:7-alpine
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data

volumes:
    redis_data:
